Show view modal to navigate user after proposal/rfp is created
NEAR-DevHub/near-prpsls-bos pull request #15
Opened 2024-05-31 14:45 UTC by Megha-Dev-19

Resolves [#795](https://github.com/NEAR-DevHub/neardevhub-bos/issues/795)

2024-06-02 07:31 UTC, petersalomonsen requested changes
Why removing the check for that the description is updated?

2024-06-02 07:33 UTC, petersalomonsen requested changes

2024-06-02 07:33 UTC, petersalomonsen commented on playwright-tests/tests/rfp.spec.js
> -    await expect(descriptionMarkdownElement).toHaveText(theNewDescription);
Why removing the check for that the description is updated?

2024-06-03 06:51 UTC, Megha-Dev-19 commented on playwright-tests/tests/rfp.spec.js
> -    await expect(descriptionMarkdownElement).toHaveText(theNewDescription);
the user won't see the updated description on create page, they will have to navigate (using the modal action) to view page to view it.

2024-06-03 10:46 UTC, petersalomonsen approved these changes

2024-06-03 10:54 UTC, merged